### ISSUE TITLE
implement JSONObject.get()

### ISSUE THREAD

**Issue by dmig** [TeskaLabs/cysimdjson#32]
Implementing method `get()` of `JSONObject` would make a better `dict` compatibility.

I'm using this library to import a large GeoJSON. Trying to feed _geometry_ object directly to `shapely` library gives an exception:
```
Traceback (most recent call last):
  File "workspace/convert-pa-json.py", line 18, in <module>
    polygon = geometry.shape(feat['geometry']['coordinates'])
  File ".local/lib/python3.9/site-packages/shapely/geometry/geo.py", line 102, in shape
    geom_type = ob.get("type").lower()
AttributeError: 'cysimdjson.JSONArray' object has no attribute 'get'
```

**Comment by ateska** [comment]
'cysimdjson.JSONArray'  is a list, not a dict.
